// Code generated by ent, DO NOT EDIT.

package recurringbill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/expenser/expense-planner/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldName, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldAmountCents, v))
}

// DueDay applies equality check predicate on the "due_day" field. It's identical to DueDayEQ.
func DueDay(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldDueDay, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldContainsFold(FieldName, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLTE(FieldAmountCents, v))
}

// DueDayEQ applies the EQ predicate on the "due_day" field.
func DueDayEQ(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldDueDay, v))
}

// DueDayNEQ applies the NEQ predicate on the "due_day" field.
func DueDayNEQ(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldDueDay, v))
}

// DueDayIn applies the In predicate on the "due_day" field.
func DueDayIn(vs ...int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldDueDay, vs...))
}

// DueDayNotIn applies the NotIn predicate on the "due_day" field.
func DueDayNotIn(vs ...int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldDueDay, vs...))
}

// DueDayGT applies the GT predicate on the "due_day" field.
func DueDayGT(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGT(FieldDueDay, v))
}

// DueDayGTE applies the GTE predicate on the "due_day" field.
func DueDayGTE(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGTE(FieldDueDay, v))
}

// DueDayLT applies the LT predicate on the "due_day" field.
func DueDayLT(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLT(FieldDueDay, v))
}

// DueDayLTE applies the LTE predicate on the "due_day" field.
func DueDayLTE(v int) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLTE(FieldDueDay, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v Frequency) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v Frequency) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...Frequency) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...Frequency) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldFrequency, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecurringBill {
	return predicate.RecurringBill(sql.FieldLTE(FieldCreatedAt, v))
}

// HasHousehold applies the HasEdge predicate on the "household" edge.
func HasHousehold() predicate.RecurringBill {
	return predicate.RecurringBill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HouseholdTable, HouseholdColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdWith applies the HasEdge predicate on the "household" edge with a given conditions (other predicates).
func HasHouseholdWith(preds ...predicate.Household) predicate.RecurringBill {
	return predicate.RecurringBill(func(s *sql.Selector) {
		step := newHouseholdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.RecurringBill {
	return predicate.RecurringBill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.Category) predicate.RecurringBill {
	return predicate.RecurringBill(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecurringBill) predicate.RecurringBill {
	return predicate.RecurringBill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecurringBill) predicate.RecurringBill {
	return predicate.RecurringBill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecurringBill) predicate.RecurringBill {
	return predicate.RecurringBill(sql.NotPredicates(p))
}
