package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/expenser/expense-planner/ent"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	return r.Client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	return r.Client.Noders(ctx, ids)
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*ent.Account, error) {
	return r.Client.Account.Query().All(ctx)
}

// Budgets is the resolver for the budgets field.
func (r *queryResolver) Budgets(ctx context.Context) ([]*ent.Budget, error) {
	return r.Client.Budget.Query().All(ctx)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*ent.Category, error) {
	return r.Client.Category.Query().All(ctx)
}

// Households is the resolver for the households field.
func (r *queryResolver) Households(ctx context.Context) ([]*ent.Household, error) {
	return r.Client.Household.Query().All(ctx)
}

// HouseholdMembers is the resolver for the householdMembers field.
func (r *queryResolver) HouseholdMembers(ctx context.Context) ([]*ent.HouseholdMember, error) {
	return r.Client.HouseholdMember.Query().All(ctx)
}

// RecurringBills is the resolver for the recurringBills field.
func (r *queryResolver) RecurringBills(ctx context.Context) ([]*ent.RecurringBill, error) {
	return r.Client.RecurringBill.Query().All(ctx)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*ent.Tag, error) {
	return r.Client.Tag.Query().All(ctx)
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*ent.Transaction, error) {
	return r.Client.Transaction.Query().All(ctx)
}

// TransactionEntries is the resolver for the transactionEntries field.
func (r *queryResolver) TransactionEntries(ctx context.Context) ([]*ent.TransactionEntry, error) {
	return r.Client.TransactionEntry.Query().All(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	return r.Client.User.Query().All(ctx)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
