package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"strings"

	"github.com/expenser/expense-planner/ent/account"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/householdmember"
	"github.com/expenser/expense-planner/ent/user"
	"github.com/expenser/expense-planner/graph/model"
	"github.com/expenser/expense-planner/internal/middleware"
	"github.com/expenser/expense-planner/internal/service"
)

// PreviewCSVImport is the resolver for the previewCSVImport field.
func (r *mutationResolver) PreviewCSVImport(ctx context.Context, csvContent string, mapping model.ColumnMappingInput, householdID int) ([]*model.ImportPreviewRow, error) {
	uc := middleware.UserFromContext(ctx)
	if uc == nil {
		return nil, fmt.Errorf("authentication required")
	}

	colMapping := service.ColumnMapping{
		DateCol:        mapping.DateCol,
		AmountCol:      mapping.AmountCol,
		DescriptionCol: mapping.DescriptionCol,
		DebitCol:       mapping.DebitCol,
		CreditCol:      mapping.CreditCol,
		DateFormat:     mapping.DateFormat,
		SkipRows:       mapping.SkipRows,
	}

	rows, err := service.ParseCSV(strings.NewReader(csvContent), colMapping)
	if err != nil {
		return nil, fmt.Errorf("parsing CSV: %w", err)
	}

	previews, err := r.ImportSvc.PreviewImport(ctx, householdID, rows)
	if err != nil {
		return nil, fmt.Errorf("previewing import: %w", err)
	}

	result := make([]*model.ImportPreviewRow, len(previews))
	for i, p := range previews {
		result[i] = &model.ImportPreviewRow{
			Date:                  p.Date,
			AmountCents:           int(p.AmountCents),
			Description:           p.Description,
			SuggestedCategoryID:   p.SuggestedCategoryID,
			SuggestedCategoryName: p.SuggestedCategoryName,
		}
	}

	return result, nil
}

// CommitCSVImport is the resolver for the commitCSVImport field.
func (r *mutationResolver) CommitCSVImport(ctx context.Context, householdID int, rows []*model.ImportRowInput) (*model.ImportSummary, error) {
	uc := middleware.UserFromContext(ctx)
	if uc == nil {
		return nil, fmt.Errorf("authentication required")
	}

	// Verify user belongs to household.
	_, err := r.Client.HouseholdMember.Query().
		Where(
			householdmember.HasUserWith(user.ID(uc.UserID)),
			householdmember.HasHouseholdWith(household.ID(householdID)),
		).
		First(ctx)
	if err != nil {
		return nil, fmt.Errorf("user is not a member of this household")
	}

	// Find default accounts.
	assetAcctID, err := r.Client.Account.Query().
		Where(
			account.HasHouseholdWith(household.ID(householdID)),
			account.TypeEQ(account.TypeAsset),
		).
		FirstID(ctx)
	if err != nil {
		return nil, fmt.Errorf("no asset account found for household")
	}

	expenseAcctID, err := r.Client.Account.Query().
		Where(
			account.HasHouseholdWith(household.ID(householdID)),
			account.TypeEQ(account.TypeExpense),
		).
		FirstID(ctx)
	if err != nil {
		return nil, fmt.Errorf("no expense account found for household")
	}

	incomeAcctID, _ := r.Client.Account.Query().
		Where(
			account.HasHouseholdWith(household.ID(householdID)),
			account.TypeEQ(account.TypeIncome),
		).
		FirstID(ctx)

	commitRows := make([]service.CommitRow, len(rows))
	for i, row := range rows {
		commitRows[i] = service.CommitRow{
			Date:        row.Date,
			AmountCents: int64(row.AmountCents),
			Description: row.Description,
			CategoryID:  row.CategoryID,
		}
	}

	summary, err := r.ImportSvc.CommitImport(ctx, service.CommitImportInput{
		HouseholdID:   householdID,
		UserID:        uc.UserID,
		AssetAcctID:   assetAcctID,
		ExpenseAcctID: expenseAcctID,
		IncomeAcctID:  incomeAcctID,
		Rows:          commitRows,
	})
	if err != nil {
		return nil, fmt.Errorf("committing import: %w", err)
	}

	return &model.ImportSummary{
		TotalImported:     summary.TotalImported,
		SkippedDuplicates: summary.SkippedDuplicates,
		TotalAmountCents:  int(summary.TotalAmountCents),
	}, nil
}

// BankPresets is the resolver for the bankPresets field.
func (r *queryResolver) BankPresets(ctx context.Context) ([]*model.BankPreset, error) {
	return []*model.BankPreset{
		{
			Name:     "KCB Bank",
			BankCode: "kcb",
			Mapping: &model.ColumnMappingOutput{
				DateCol:        0,
				AmountCol:      intPtr(2),
				DescriptionCol: 1,
				DateFormat:     "02/01/2006",
				SkipRows:       1,
			},
		},
		{
			Name:     "Equity Bank",
			BankCode: "equity",
			Mapping: &model.ColumnMappingOutput{
				DateCol:        0,
				DescriptionCol: 1,
				DebitCol:       intPtr(2),
				CreditCol:      intPtr(3),
				DateFormat:     "02-Jan-2006",
				SkipRows:       1,
			},
		},
		{
			Name:     "M-PESA",
			BankCode: "mpesa",
			Mapping: &model.ColumnMappingOutput{
				DateCol:        1,
				DescriptionCol: 2,
				CreditCol:      intPtr(4),
				DebitCol:       intPtr(5),
				DateFormat:     "02/01/2006 15:04:05",
				SkipRows:       1,
			},
		},
	}, nil
}
