package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/expenser/expense-planner/graph/model"
	"github.com/expenser/expense-planner/internal/middleware"
)

// SpendingByCategory is the resolver for the spendingByCategory field.
func (r *queryResolver) SpendingByCategory(ctx context.Context, householdID int, startDate time.Time, endDate time.Time) ([]*model.CategorySpend, error) {
	uc := middleware.UserFromContext(ctx)
	if uc == nil {
		return nil, fmt.Errorf("authentication required")
	}

	results, err := r.ReportSvc.SpendingByCategory(ctx, householdID, startDate, endDate)
	if err != nil {
		return nil, err
	}

	out := make([]*model.CategorySpend, len(results))
	for i, cs := range results {
		out[i] = &model.CategorySpend{
			CategoryID: cs.CategoryID,
			Name:       cs.Name,
			TotalCents: int(cs.TotalCents),
			Percentage: cs.Percentage,
		}
	}
	return out, nil
}

// MonthlyTrend is the resolver for the monthlyTrend field.
func (r *queryResolver) MonthlyTrend(ctx context.Context, householdID int, months int) ([]*model.MonthSummary, error) {
	uc := middleware.UserFromContext(ctx)
	if uc == nil {
		return nil, fmt.Errorf("authentication required")
	}

	results, err := r.ReportSvc.MonthlyTrend(ctx, householdID, months, time.Now().UTC())
	if err != nil {
		return nil, err
	}

	out := make([]*model.MonthSummary, len(results))
	for i, ms := range results {
		out[i] = &model.MonthSummary{
			Month:        ms.Month,
			IncomeCents:  int(ms.IncomeCents),
			ExpenseCents: int(ms.ExpenseCents),
			NetCents:     int(ms.NetCents),
		}
	}
	return out, nil
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context, householdID int) (*model.DashboardSummary, error) {
	uc := middleware.UserFromContext(ctx)
	if uc == nil {
		return nil, fmt.Errorf("authentication required")
	}

	ds, err := r.ReportSvc.GetDashboardSummary(ctx, householdID)
	if err != nil {
		return nil, err
	}

	return &model.DashboardSummary{
		TotalBalanceCents:  int(ds.TotalBalanceCents),
		TotalIncomeCents:   int(ds.TotalIncomeCents),
		TotalSpendingCents: int(ds.TotalSpendingCents),
		SafeToSpendCents:   int(ds.SafeToSpendCents),
		RecentTransactions: ds.RecentTransactions,
	}, nil
}
