// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/expenser/expense-planner/ent"
)

type AuthPayload struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	User         *ent.User `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
