// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"asset", "income", "expense", "liability"}},
		{Name: "balance_cents", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "household_accounts", Type: field.TypeInt},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_households_accounts",
				Columns:    []*schema.Column{AccountsColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "account_name_household_accounts",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[1], AccountsColumns[5]},
			},
		},
	}
	// BudgetsColumns holds the columns for the "budgets" table.
	BudgetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "month", Type: field.TypeString},
		{Name: "amount_cents", Type: field.TypeInt64},
		{Name: "rollover", Type: field.TypeBool, Default: false},
		{Name: "category_budgets", Type: field.TypeInt},
		{Name: "household_budgets", Type: field.TypeInt},
	}
	// BudgetsTable holds the schema information for the "budgets" table.
	BudgetsTable = &schema.Table{
		Name:       "budgets",
		Columns:    BudgetsColumns,
		PrimaryKey: []*schema.Column{BudgetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "budgets_categories_budgets",
				Columns:    []*schema.Column{BudgetsColumns[4]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "budgets_households_budgets",
				Columns:    []*schema.Column{BudgetsColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "budget_month_household_budgets_category_budgets",
				Unique:  true,
				Columns: []*schema.Column{BudgetsColumns[1], BudgetsColumns[5], BudgetsColumns[4]},
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "category_children", Type: field.TypeInt, Nullable: true},
		{Name: "household_categories", Type: field.TypeInt},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_categories_children",
				Columns:    []*schema.Column{CategoriesColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "categories_households_categories",
				Columns:    []*schema.Column{CategoriesColumns[7]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// HouseholdsColumns holds the columns for the "households" table.
	HouseholdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "base_currency", Type: field.TypeString, Default: "KES"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// HouseholdsTable holds the schema information for the "households" table.
	HouseholdsTable = &schema.Table{
		Name:       "households",
		Columns:    HouseholdsColumns,
		PrimaryKey: []*schema.Column{HouseholdsColumns[0]},
	}
	// HouseholdMembersColumns holds the columns for the "household_members" table.
	HouseholdMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "member"}, Default: "member"},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "household_members", Type: field.TypeInt},
		{Name: "user_members", Type: field.TypeInt},
	}
	// HouseholdMembersTable holds the schema information for the "household_members" table.
	HouseholdMembersTable = &schema.Table{
		Name:       "household_members",
		Columns:    HouseholdMembersColumns,
		PrimaryKey: []*schema.Column{HouseholdMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "household_members_households_members",
				Columns:    []*schema.Column{HouseholdMembersColumns[3]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "household_members_users_members",
				Columns:    []*schema.Column{HouseholdMembersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InviteCodesColumns holds the columns for the "invite_codes" table.
	InviteCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "household_invite_codes", Type: field.TypeInt},
		{Name: "user_invite_codes", Type: field.TypeInt},
	}
	// InviteCodesTable holds the schema information for the "invite_codes" table.
	InviteCodesTable = &schema.Table{
		Name:       "invite_codes",
		Columns:    InviteCodesColumns,
		PrimaryKey: []*schema.Column{InviteCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invite_codes_households_invite_codes",
				Columns:    []*schema.Column{InviteCodesColumns[5]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "invite_codes_users_invite_codes",
				Columns:    []*schema.Column{InviteCodesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PlaceholdersColumns holds the columns for the "placeholders" table.
	PlaceholdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// PlaceholdersTable holds the schema information for the "placeholders" table.
	PlaceholdersTable = &schema.Table{
		Name:       "placeholders",
		Columns:    PlaceholdersColumns,
		PrimaryKey: []*schema.Column{PlaceholdersColumns[0]},
	}
	// RecurringBillsColumns holds the columns for the "recurring_bills" table.
	RecurringBillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "amount_cents", Type: field.TypeInt64},
		{Name: "due_day", Type: field.TypeInt},
		{Name: "frequency", Type: field.TypeEnum, Enums: []string{"monthly", "weekly", "annual"}, Default: "monthly"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "paid", "overdue"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "category_recurring_bills", Type: field.TypeInt, Nullable: true},
		{Name: "household_recurring_bills", Type: field.TypeInt},
	}
	// RecurringBillsTable holds the schema information for the "recurring_bills" table.
	RecurringBillsTable = &schema.Table{
		Name:       "recurring_bills",
		Columns:    RecurringBillsColumns,
		PrimaryKey: []*schema.Column{RecurringBillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recurring_bills_categories_recurring_bills",
				Columns:    []*schema.Column{RecurringBillsColumns[7]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "recurring_bills_households_recurring_bills",
				Columns:    []*schema.Column{RecurringBillsColumns[8]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "household_tags", Type: field.TypeInt},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_households_tags",
				Columns:    []*schema.Column{TagsColumns[3]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tag_name_household_tags",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[1], TagsColumns[3]},
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "posted"}, Default: "posted"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "category_transactions", Type: field.TypeInt, Nullable: true},
		{Name: "household_transactions", Type: field.TypeInt},
		{Name: "user_transactions", Type: field.TypeInt},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[5]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "transactions_households_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{HouseholdsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_users_transactions",
				Columns:    []*schema.Column{TransactionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionEntriesColumns holds the columns for the "transaction_entries" table.
	TransactionEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount_cents", Type: field.TypeInt64},
		{Name: "account_entries", Type: field.TypeInt},
		{Name: "transaction_entries", Type: field.TypeInt},
	}
	// TransactionEntriesTable holds the schema information for the "transaction_entries" table.
	TransactionEntriesTable = &schema.Table{
		Name:       "transaction_entries",
		Columns:    TransactionEntriesColumns,
		PrimaryKey: []*schema.Column{TransactionEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transaction_entries_accounts_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[2]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transaction_entries_transactions_entries",
				Columns:    []*schema.Column{TransactionEntriesColumns[3]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// TagTransactionsColumns holds the columns for the "tag_transactions" table.
	TagTransactionsColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "transaction_id", Type: field.TypeInt},
	}
	// TagTransactionsTable holds the schema information for the "tag_transactions" table.
	TagTransactionsTable = &schema.Table{
		Name:       "tag_transactions",
		Columns:    TagTransactionsColumns,
		PrimaryKey: []*schema.Column{TagTransactionsColumns[0], TagTransactionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_transactions_tag_id",
				Columns:    []*schema.Column{TagTransactionsColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_transactions_transaction_id",
				Columns:    []*schema.Column{TagTransactionsColumns[1]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		BudgetsTable,
		CategoriesTable,
		HouseholdsTable,
		HouseholdMembersTable,
		InviteCodesTable,
		PlaceholdersTable,
		RecurringBillsTable,
		TagsTable,
		TransactionsTable,
		TransactionEntriesTable,
		UsersTable,
		TagTransactionsTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = HouseholdsTable
	BudgetsTable.ForeignKeys[0].RefTable = CategoriesTable
	BudgetsTable.ForeignKeys[1].RefTable = HouseholdsTable
	CategoriesTable.ForeignKeys[0].RefTable = CategoriesTable
	CategoriesTable.ForeignKeys[1].RefTable = HouseholdsTable
	HouseholdMembersTable.ForeignKeys[0].RefTable = HouseholdsTable
	HouseholdMembersTable.ForeignKeys[1].RefTable = UsersTable
	InviteCodesTable.ForeignKeys[0].RefTable = HouseholdsTable
	InviteCodesTable.ForeignKeys[1].RefTable = UsersTable
	RecurringBillsTable.ForeignKeys[0].RefTable = CategoriesTable
	RecurringBillsTable.ForeignKeys[1].RefTable = HouseholdsTable
	TagsTable.ForeignKeys[0].RefTable = HouseholdsTable
	TransactionsTable.ForeignKeys[0].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[1].RefTable = HouseholdsTable
	TransactionsTable.ForeignKeys[2].RefTable = UsersTable
	TransactionEntriesTable.ForeignKeys[0].RefTable = AccountsTable
	TransactionEntriesTable.ForeignKeys[1].RefTable = TransactionsTable
	TagTransactionsTable.ForeignKeys[0].RefTable = TagsTable
	TagTransactionsTable.ForeignKeys[1].RefTable = TransactionsTable
}
