// Code generated by ent, DO NOT EDIT.

package household

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/expenser/expense-planner/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldName, v))
}

// BaseCurrency applies equality check predicate on the "base_currency" field. It's identical to BaseCurrencyEQ.
func BaseCurrency(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldBaseCurrency, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Household {
	return predicate.Household(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Household {
	return predicate.Household(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Household {
	return predicate.Household(sql.FieldContainsFold(FieldName, v))
}

// BaseCurrencyEQ applies the EQ predicate on the "base_currency" field.
func BaseCurrencyEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldBaseCurrency, v))
}

// BaseCurrencyNEQ applies the NEQ predicate on the "base_currency" field.
func BaseCurrencyNEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldBaseCurrency, v))
}

// BaseCurrencyIn applies the In predicate on the "base_currency" field.
func BaseCurrencyIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyNotIn applies the NotIn predicate on the "base_currency" field.
func BaseCurrencyNotIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyGT applies the GT predicate on the "base_currency" field.
func BaseCurrencyGT(v string) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldBaseCurrency, v))
}

// BaseCurrencyGTE applies the GTE predicate on the "base_currency" field.
func BaseCurrencyGTE(v string) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldBaseCurrency, v))
}

// BaseCurrencyLT applies the LT predicate on the "base_currency" field.
func BaseCurrencyLT(v string) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldBaseCurrency, v))
}

// BaseCurrencyLTE applies the LTE predicate on the "base_currency" field.
func BaseCurrencyLTE(v string) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldBaseCurrency, v))
}

// BaseCurrencyContains applies the Contains predicate on the "base_currency" field.
func BaseCurrencyContains(v string) predicate.Household {
	return predicate.Household(sql.FieldContains(FieldBaseCurrency, v))
}

// BaseCurrencyHasPrefix applies the HasPrefix predicate on the "base_currency" field.
func BaseCurrencyHasPrefix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasPrefix(FieldBaseCurrency, v))
}

// BaseCurrencyHasSuffix applies the HasSuffix predicate on the "base_currency" field.
func BaseCurrencyHasSuffix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasSuffix(FieldBaseCurrency, v))
}

// BaseCurrencyEqualFold applies the EqualFold predicate on the "base_currency" field.
func BaseCurrencyEqualFold(v string) predicate.Household {
	return predicate.Household(sql.FieldEqualFold(FieldBaseCurrency, v))
}

// BaseCurrencyContainsFold applies the ContainsFold predicate on the "base_currency" field.
func BaseCurrencyContainsFold(v string) predicate.Household {
	return predicate.Household(sql.FieldContainsFold(FieldBaseCurrency, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.HouseholdMember) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCategories applies the HasEdge predicate on the "categories" edge.
func HasCategories() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CategoriesTable, CategoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoriesWith applies the HasEdge predicate on the "categories" edge with a given conditions (other predicates).
func HasCategoriesWith(preds ...predicate.Category) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBudgets applies the HasEdge predicate on the "budgets" edge.
func HasBudgets() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BudgetsTable, BudgetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBudgetsWith applies the HasEdge predicate on the "budgets" edge with a given conditions (other predicates).
func HasBudgetsWith(preds ...predicate.Budget) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newBudgetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TagsTable, TagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecurringBills applies the HasEdge predicate on the "recurring_bills" edge.
func HasRecurringBills() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecurringBillsTable, RecurringBillsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecurringBillsWith applies the HasEdge predicate on the "recurring_bills" edge with a given conditions (other predicates).
func HasRecurringBillsWith(preds ...predicate.RecurringBill) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newRecurringBillsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Household) predicate.Household {
	return predicate.Household(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Household) predicate.Household {
	return predicate.Household(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Household) predicate.Household {
	return predicate.Household(sql.NotPredicates(p))
}
