// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/expenser/expense-planner/ent/category"
	"github.com/expenser/expense-planner/ent/household"
)

// Category is the model entity for the Category schema.
type Category struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon *string `json:"icon,omitempty"`
	// Color holds the value of the "color" field.
	Color *string `json:"color,omitempty"`
	// IsSystem holds the value of the "is_system" field.
	IsSystem bool `json:"is_system,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CategoryQuery when eager-loading is set.
	Edges                CategoryEdges `json:"edges"`
	category_children    *int
	household_categories *int
	selectValues         sql.SelectValues
}

// CategoryEdges holds the relations/edges for other nodes in the graph.
type CategoryEdges struct {
	// Household holds the value of the household edge.
	Household *Household `json:"household,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Category `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Category `json:"children,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*Transaction `json:"transactions,omitempty"`
	// Budgets holds the value of the budgets edge.
	Budgets []*Budget `json:"budgets,omitempty"`
	// RecurringBills holds the value of the recurring_bills edge.
	RecurringBills []*RecurringBill `json:"recurring_bills,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
	// totalCount holds the count of the edges above.
	totalCount [6]map[string]int

	namedChildren       map[string][]*Category
	namedTransactions   map[string][]*Transaction
	namedBudgets        map[string][]*Budget
	namedRecurringBills map[string][]*RecurringBill
}

// HouseholdOrErr returns the Household value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CategoryEdges) HouseholdOrErr() (*Household, error) {
	if e.Household != nil {
		return e.Household, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: household.Label}
	}
	return nil, &NotLoadedError{edge: "household"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CategoryEdges) ParentOrErr() (*Category, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) ChildrenOrErr() ([]*Category, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) TransactionsOrErr() ([]*Transaction, error) {
	if e.loadedTypes[3] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// BudgetsOrErr returns the Budgets value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) BudgetsOrErr() ([]*Budget, error) {
	if e.loadedTypes[4] {
		return e.Budgets, nil
	}
	return nil, &NotLoadedError{edge: "budgets"}
}

// RecurringBillsOrErr returns the RecurringBills value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) RecurringBillsOrErr() ([]*RecurringBill, error) {
	if e.loadedTypes[5] {
		return e.RecurringBills, nil
	}
	return nil, &NotLoadedError{edge: "recurring_bills"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Category) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case category.FieldIsSystem:
			values[i] = new(sql.NullBool)
		case category.FieldID:
			values[i] = new(sql.NullInt64)
		case category.FieldName, category.FieldIcon, category.FieldColor:
			values[i] = new(sql.NullString)
		case category.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case category.ForeignKeys[0]: // category_children
			values[i] = new(sql.NullInt64)
		case category.ForeignKeys[1]: // household_categories
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Category fields.
func (_m *Category) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case category.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case category.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case category.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = new(string)
				*_m.Icon = value.String
			}
		case category.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = new(string)
				*_m.Color = value.String
			}
		case category.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = value.Bool
			}
		case category.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case category.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field category_children", value)
			} else if value.Valid {
				_m.category_children = new(int)
				*_m.category_children = int(value.Int64)
			}
		case category.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field household_categories", value)
			} else if value.Valid {
				_m.household_categories = new(int)
				*_m.household_categories = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Category.
// This includes values selected through modifiers, order, etc.
func (_m *Category) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHousehold queries the "household" edge of the Category entity.
func (_m *Category) QueryHousehold() *HouseholdQuery {
	return NewCategoryClient(_m.config).QueryHousehold(_m)
}

// QueryParent queries the "parent" edge of the Category entity.
func (_m *Category) QueryParent() *CategoryQuery {
	return NewCategoryClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Category entity.
func (_m *Category) QueryChildren() *CategoryQuery {
	return NewCategoryClient(_m.config).QueryChildren(_m)
}

// QueryTransactions queries the "transactions" edge of the Category entity.
func (_m *Category) QueryTransactions() *TransactionQuery {
	return NewCategoryClient(_m.config).QueryTransactions(_m)
}

// QueryBudgets queries the "budgets" edge of the Category entity.
func (_m *Category) QueryBudgets() *BudgetQuery {
	return NewCategoryClient(_m.config).QueryBudgets(_m)
}

// QueryRecurringBills queries the "recurring_bills" edge of the Category entity.
func (_m *Category) QueryRecurringBills() *RecurringBillQuery {
	return NewCategoryClient(_m.config).QueryRecurringBills(_m)
}

// Update returns a builder for updating this Category.
// Note that you need to call Category.Unwrap() before calling this method if this Category
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Category) Update() *CategoryUpdateOne {
	return NewCategoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Category entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Category) Unwrap() *Category {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Category is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Category) String() string {
	var builder strings.Builder
	builder.WriteString("Category(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Icon; v != nil {
		builder.WriteString("icon=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Color; v != nil {
		builder.WriteString("color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_system=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystem))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedChildren returns the Children named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Category) NamedChildren(name string) ([]*Category, error) {
	if _m.Edges.namedChildren == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedChildren[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Category) appendNamedChildren(name string, edges ...*Category) {
	if _m.Edges.namedChildren == nil {
		_m.Edges.namedChildren = make(map[string][]*Category)
	}
	if len(edges) == 0 {
		_m.Edges.namedChildren[name] = []*Category{}
	} else {
		_m.Edges.namedChildren[name] = append(_m.Edges.namedChildren[name], edges...)
	}
}

// NamedTransactions returns the Transactions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Category) NamedTransactions(name string) ([]*Transaction, error) {
	if _m.Edges.namedTransactions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTransactions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Category) appendNamedTransactions(name string, edges ...*Transaction) {
	if _m.Edges.namedTransactions == nil {
		_m.Edges.namedTransactions = make(map[string][]*Transaction)
	}
	if len(edges) == 0 {
		_m.Edges.namedTransactions[name] = []*Transaction{}
	} else {
		_m.Edges.namedTransactions[name] = append(_m.Edges.namedTransactions[name], edges...)
	}
}

// NamedBudgets returns the Budgets named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Category) NamedBudgets(name string) ([]*Budget, error) {
	if _m.Edges.namedBudgets == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedBudgets[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Category) appendNamedBudgets(name string, edges ...*Budget) {
	if _m.Edges.namedBudgets == nil {
		_m.Edges.namedBudgets = make(map[string][]*Budget)
	}
	if len(edges) == 0 {
		_m.Edges.namedBudgets[name] = []*Budget{}
	} else {
		_m.Edges.namedBudgets[name] = append(_m.Edges.namedBudgets[name], edges...)
	}
}

// NamedRecurringBills returns the RecurringBills named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Category) NamedRecurringBills(name string) ([]*RecurringBill, error) {
	if _m.Edges.namedRecurringBills == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRecurringBills[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Category) appendNamedRecurringBills(name string, edges ...*RecurringBill) {
	if _m.Edges.namedRecurringBills == nil {
		_m.Edges.namedRecurringBills = make(map[string][]*RecurringBill)
	}
	if len(edges) == 0 {
		_m.Edges.namedRecurringBills[name] = []*RecurringBill{}
	} else {
		_m.Edges.namedRecurringBills[name] = append(_m.Edges.namedRecurringBills[name], edges...)
	}
}

// Categories is a parsable slice of Category.
type Categories []*Category
