// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Account) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Category) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Category) Parent(ctx context.Context) (*Category, error) {
	result, err := _m.Edges.ParentOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryParent().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Category) Children(ctx context.Context) (result []*Category, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChildren(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChildrenOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChildren().All(ctx)
	}
	return result, err
}

func (_m *Household) Members(ctx context.Context) (result []*HouseholdMember, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMembers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MembersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMembers().All(ctx)
	}
	return result, err
}

func (_m *Household) Accounts(ctx context.Context) (result []*Account, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAccounts().All(ctx)
	}
	return result, err
}

func (_m *Household) Categories(ctx context.Context) (result []*Category, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCategories(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CategoriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCategories().All(ctx)
	}
	return result, err
}

func (_m *HouseholdMember) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *HouseholdMember) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *User) Members(ctx context.Context) (result []*HouseholdMember, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMembers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MembersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMembers().All(ctx)
	}
	return result, err
}
