// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/householdmember"
	"github.com/expenser/expense-planner/ent/predicate"
	"github.com/expenser/expense-planner/ent/user"
)

// HouseholdMemberQuery is the builder for querying HouseholdMember entities.
type HouseholdMemberQuery struct {
	config
	ctx           *QueryContext
	order         []householdmember.OrderOption
	inters        []Interceptor
	predicates    []predicate.HouseholdMember
	withHousehold *HouseholdQuery
	withUser      *UserQuery
	withFKs       bool
	modifiers     []func(*sql.Selector)
	loadTotal     []func(context.Context, []*HouseholdMember) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HouseholdMemberQuery builder.
func (_q *HouseholdMemberQuery) Where(ps ...predicate.HouseholdMember) *HouseholdMemberQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HouseholdMemberQuery) Limit(limit int) *HouseholdMemberQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HouseholdMemberQuery) Offset(offset int) *HouseholdMemberQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HouseholdMemberQuery) Unique(unique bool) *HouseholdMemberQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HouseholdMemberQuery) Order(o ...householdmember.OrderOption) *HouseholdMemberQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *HouseholdMemberQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(householdmember.Table, householdmember.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, householdmember.HouseholdTable, householdmember.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *HouseholdMemberQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(householdmember.Table, householdmember.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, householdmember.UserTable, householdmember.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HouseholdMember entity from the query.
// Returns a *NotFoundError when no HouseholdMember was found.
func (_q *HouseholdMemberQuery) First(ctx context.Context) (*HouseholdMember, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{householdmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HouseholdMemberQuery) FirstX(ctx context.Context) *HouseholdMember {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HouseholdMember ID from the query.
// Returns a *NotFoundError when no HouseholdMember ID was found.
func (_q *HouseholdMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{householdmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HouseholdMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HouseholdMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HouseholdMember entity is found.
// Returns a *NotFoundError when no HouseholdMember entities are found.
func (_q *HouseholdMemberQuery) Only(ctx context.Context) (*HouseholdMember, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{householdmember.Label}
	default:
		return nil, &NotSingularError{householdmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HouseholdMemberQuery) OnlyX(ctx context.Context) *HouseholdMember {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HouseholdMember ID in the query.
// Returns a *NotSingularError when more than one HouseholdMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HouseholdMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{householdmember.Label}
	default:
		err = &NotSingularError{householdmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HouseholdMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HouseholdMembers.
func (_q *HouseholdMemberQuery) All(ctx context.Context) ([]*HouseholdMember, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HouseholdMember, *HouseholdMemberQuery]()
	return withInterceptors[[]*HouseholdMember](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HouseholdMemberQuery) AllX(ctx context.Context) []*HouseholdMember {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HouseholdMember IDs.
func (_q *HouseholdMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(householdmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HouseholdMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HouseholdMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HouseholdMemberQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HouseholdMemberQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HouseholdMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HouseholdMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HouseholdMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HouseholdMemberQuery) Clone() *HouseholdMemberQuery {
	if _q == nil {
		return nil
	}
	return &HouseholdMemberQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]householdmember.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.HouseholdMember{}, _q.predicates...),
		withHousehold: _q.withHousehold.Clone(),
		withUser:      _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HouseholdMemberQuery) WithHousehold(opts ...func(*HouseholdQuery)) *HouseholdMemberQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HouseholdMemberQuery) WithUser(opts ...func(*UserQuery)) *HouseholdMemberQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Role householdmember.Role `json:"role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HouseholdMember.Query().
//		GroupBy(householdmember.FieldRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HouseholdMemberQuery) GroupBy(field string, fields ...string) *HouseholdMemberGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HouseholdMemberGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = householdmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Role householdmember.Role `json:"role,omitempty"`
//	}
//
//	client.HouseholdMember.Query().
//		Select(householdmember.FieldRole).
//		Scan(ctx, &v)
func (_q *HouseholdMemberQuery) Select(fields ...string) *HouseholdMemberSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HouseholdMemberSelect{HouseholdMemberQuery: _q}
	sbuild.label = householdmember.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HouseholdMemberSelect configured with the given aggregations.
func (_q *HouseholdMemberQuery) Aggregate(fns ...AggregateFunc) *HouseholdMemberSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HouseholdMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !householdmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *HouseholdMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HouseholdMember, error) {
	var (
		nodes       = []*HouseholdMember{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withHousehold != nil,
			_q.withUser != nil,
		}
	)
	if _q.withHousehold != nil || _q.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, householdmember.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HouseholdMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HouseholdMember{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *HouseholdMember, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *HouseholdMember, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HouseholdMemberQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*HouseholdMember, init func(*HouseholdMember), assign func(*HouseholdMember, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HouseholdMember)
	for i := range nodes {
		if nodes[i].household_members == nil {
			continue
		}
		fk := *nodes[i].household_members
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_members" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *HouseholdMemberQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*HouseholdMember, init func(*HouseholdMember), assign func(*HouseholdMember, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HouseholdMember)
	for i := range nodes {
		if nodes[i].user_members == nil {
			continue
		}
		fk := *nodes[i].user_members
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_members" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *HouseholdMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HouseholdMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(householdmember.Table, householdmember.Columns, sqlgraph.NewFieldSpec(householdmember.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, householdmember.FieldID)
		for i := range fields {
			if fields[i] != householdmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HouseholdMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(householdmember.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = householdmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HouseholdMemberGroupBy is the group-by builder for HouseholdMember entities.
type HouseholdMemberGroupBy struct {
	selector
	build *HouseholdMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HouseholdMemberGroupBy) Aggregate(fns ...AggregateFunc) *HouseholdMemberGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HouseholdMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HouseholdMemberQuery, *HouseholdMemberGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HouseholdMemberGroupBy) sqlScan(ctx context.Context, root *HouseholdMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HouseholdMemberSelect is the builder for selecting fields of HouseholdMember entities.
type HouseholdMemberSelect struct {
	*HouseholdMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HouseholdMemberSelect) Aggregate(fns ...AggregateFunc) *HouseholdMemberSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HouseholdMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HouseholdMemberQuery, *HouseholdMemberSelect](ctx, _s.HouseholdMemberQuery, _s, _s.inters, v)
}

func (_s *HouseholdMemberSelect) sqlScan(ctx context.Context, root *HouseholdMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
