// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/account"
	"github.com/expenser/expense-planner/ent/category"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/householdmember"
	"github.com/expenser/expense-planner/ent/transaction"
)

// HouseholdCreate is the builder for creating a Household entity.
type HouseholdCreate struct {
	config
	mutation *HouseholdMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *HouseholdCreate) SetName(v string) *HouseholdCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseCurrency sets the "base_currency" field.
func (_c *HouseholdCreate) SetBaseCurrency(v string) *HouseholdCreate {
	_c.mutation.SetBaseCurrency(v)
	return _c
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_c *HouseholdCreate) SetNillableBaseCurrency(v *string) *HouseholdCreate {
	if v != nil {
		_c.SetBaseCurrency(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HouseholdCreate) SetCreatedAt(v time.Time) *HouseholdCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HouseholdCreate) SetNillableCreatedAt(v *time.Time) *HouseholdCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the HouseholdMember entity by IDs.
func (_c *HouseholdCreate) AddMemberIDs(ids ...int) *HouseholdCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the HouseholdMember entity.
func (_c *HouseholdCreate) AddMembers(v ...*HouseholdMember) *HouseholdCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *HouseholdCreate) AddAccountIDs(ids ...int) *HouseholdCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *HouseholdCreate) AddAccounts(v ...*Account) *HouseholdCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_c *HouseholdCreate) AddCategoryIDs(ids ...int) *HouseholdCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the Category entity.
func (_c *HouseholdCreate) AddCategories(v ...*Category) *HouseholdCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *HouseholdCreate) AddTransactionIDs(ids ...int) *HouseholdCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *HouseholdCreate) AddTransactions(v ...*Transaction) *HouseholdCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// Mutation returns the HouseholdMutation object of the builder.
func (_c *HouseholdCreate) Mutation() *HouseholdMutation {
	return _c.mutation
}

// Save creates the Household in the database.
func (_c *HouseholdCreate) Save(ctx context.Context) (*Household, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HouseholdCreate) SaveX(ctx context.Context) *Household {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HouseholdCreate) defaults() {
	if _, ok := _c.mutation.BaseCurrency(); !ok {
		v := household.DefaultBaseCurrency
		_c.mutation.SetBaseCurrency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := household.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HouseholdCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Household.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := household.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Household.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseCurrency(); !ok {
		return &ValidationError{Name: "base_currency", err: errors.New(`ent: missing required field "Household.base_currency"`)}
	}
	if v, ok := _c.mutation.BaseCurrency(); ok {
		if err := household.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "Household.base_currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Household.created_at"`)}
	}
	return nil
}

func (_c *HouseholdCreate) sqlSave(ctx context.Context) (*Household, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HouseholdCreate) createSpec() (*Household, *sqlgraph.CreateSpec) {
	var (
		_node = &Household{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(household.Table, sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(household.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseCurrency(); ok {
		_spec.SetField(household.FieldBaseCurrency, field.TypeString, value)
		_node.BaseCurrency = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(household.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.MembersTable,
			Columns: []string{household.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.CategoriesTable,
			Columns: []string{household.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HouseholdCreateBulk is the builder for creating many Household entities in bulk.
type HouseholdCreateBulk struct {
	config
	err      error
	builders []*HouseholdCreate
}

// Save creates the Household entities in the database.
func (_c *HouseholdCreateBulk) Save(ctx context.Context) ([]*Household, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Household, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HouseholdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HouseholdCreateBulk) SaveX(ctx context.Context) []*Household {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
