// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/householdmember"
	"github.com/expenser/expense-planner/ent/user"
)

// HouseholdMemberCreate is the builder for creating a HouseholdMember entity.
type HouseholdMemberCreate struct {
	config
	mutation *HouseholdMemberMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (_c *HouseholdMemberCreate) SetRole(v householdmember.Role) *HouseholdMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *HouseholdMemberCreate) SetNillableRole(v *householdmember.Role) *HouseholdMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *HouseholdMemberCreate) SetJoinedAt(v time.Time) *HouseholdMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *HouseholdMemberCreate) SetNillableJoinedAt(v *time.Time) *HouseholdMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_c *HouseholdMemberCreate) SetHouseholdID(id int) *HouseholdMemberCreate {
	_c.mutation.SetHouseholdID(id)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *HouseholdMemberCreate) SetHousehold(v *Household) *HouseholdMemberCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *HouseholdMemberCreate) SetUserID(id int) *HouseholdMemberCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *HouseholdMemberCreate) SetUser(v *User) *HouseholdMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the HouseholdMemberMutation object of the builder.
func (_c *HouseholdMemberCreate) Mutation() *HouseholdMemberMutation {
	return _c.mutation
}

// Save creates the HouseholdMember in the database.
func (_c *HouseholdMemberCreate) Save(ctx context.Context) (*HouseholdMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HouseholdMemberCreate) SaveX(ctx context.Context) *HouseholdMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HouseholdMemberCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := householdmember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := householdmember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HouseholdMemberCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "HouseholdMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := householdmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "HouseholdMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "HouseholdMember.joined_at"`)}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "HouseholdMember.household"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "HouseholdMember.user"`)}
	}
	return nil
}

func (_c *HouseholdMemberCreate) sqlSave(ctx context.Context) (*HouseholdMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HouseholdMemberCreate) createSpec() (*HouseholdMember, *sqlgraph.CreateSpec) {
	var (
		_node = &HouseholdMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(householdmember.Table, sqlgraph.NewFieldSpec(householdmember.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(householdmember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(householdmember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   householdmember.HouseholdTable,
			Columns: []string{householdmember.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.household_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   householdmember.UserTable,
			Columns: []string{householdmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HouseholdMemberCreateBulk is the builder for creating many HouseholdMember entities in bulk.
type HouseholdMemberCreateBulk struct {
	config
	err      error
	builders []*HouseholdMemberCreate
}

// Save creates the HouseholdMember entities in the database.
func (_c *HouseholdMemberCreateBulk) Save(ctx context.Context) ([]*HouseholdMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HouseholdMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HouseholdMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HouseholdMemberCreateBulk) SaveX(ctx context.Context) []*HouseholdMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
