// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/invitecode"
	"github.com/expenser/expense-planner/ent/predicate"
	"github.com/expenser/expense-planner/ent/user"
)

// InviteCodeUpdate is the builder for updating InviteCode entities.
type InviteCodeUpdate struct {
	config
	hooks    []Hook
	mutation *InviteCodeMutation
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (_u *InviteCodeUpdate) Where(ps ...predicate.InviteCode) *InviteCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *InviteCodeUpdate) SetCode(v string) *InviteCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableCode(v *string) *InviteCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteCodeUpdate) SetExpiresAt(v time.Time) *InviteCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableExpiresAt(v *time.Time) *InviteCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *InviteCodeUpdate) SetUsed(v bool) *InviteCodeUpdate {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableUsed(v *bool) *InviteCodeUpdate {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_u *InviteCodeUpdate) SetHouseholdID(id int) *InviteCodeUpdate {
	_u.mutation.SetHouseholdID(id)
	return _u
}

// SetHousehold sets the "household" edge to the Household entity.
func (_u *InviteCodeUpdate) SetHousehold(v *Household) *InviteCodeUpdate {
	return _u.SetHouseholdID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *InviteCodeUpdate) SetCreatedByID(id int) *InviteCodeUpdate {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *InviteCodeUpdate) SetCreatedBy(v *User) *InviteCodeUpdate {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_u *InviteCodeUpdate) Mutation() *InviteCodeMutation {
	return _u.mutation
}

// ClearHousehold clears the "household" edge to the Household entity.
func (_u *InviteCodeUpdate) ClearHousehold() *InviteCodeUpdate {
	_u.mutation.ClearHousehold()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *InviteCodeUpdate) ClearCreatedBy() *InviteCodeUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteCode.household"`)
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteCode.created_by"`)
	}
	return nil
}

func (_u *InviteCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitecode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(invitecode.FieldUsed, field.TypeBool, value)
	}
	if _u.mutation.HouseholdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.HouseholdTable,
			Columns: []string{invitecode.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.HouseholdTable,
			Columns: []string{invitecode.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.CreatedByTable,
			Columns: []string{invitecode.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.CreatedByTable,
			Columns: []string{invitecode.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteCodeUpdateOne is the builder for updating a single InviteCode entity.
type InviteCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteCodeMutation
}

// SetCode sets the "code" field.
func (_u *InviteCodeUpdateOne) SetCode(v string) *InviteCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableCode(v *string) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteCodeUpdateOne) SetExpiresAt(v time.Time) *InviteCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *InviteCodeUpdateOne) SetUsed(v bool) *InviteCodeUpdateOne {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableUsed(v *bool) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_u *InviteCodeUpdateOne) SetHouseholdID(id int) *InviteCodeUpdateOne {
	_u.mutation.SetHouseholdID(id)
	return _u
}

// SetHousehold sets the "household" edge to the Household entity.
func (_u *InviteCodeUpdateOne) SetHousehold(v *Household) *InviteCodeUpdateOne {
	return _u.SetHouseholdID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *InviteCodeUpdateOne) SetCreatedByID(id int) *InviteCodeUpdateOne {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *InviteCodeUpdateOne) SetCreatedBy(v *User) *InviteCodeUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_u *InviteCodeUpdateOne) Mutation() *InviteCodeMutation {
	return _u.mutation
}

// ClearHousehold clears the "household" edge to the Household entity.
func (_u *InviteCodeUpdateOne) ClearHousehold() *InviteCodeUpdateOne {
	_u.mutation.ClearHousehold()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *InviteCodeUpdateOne) ClearCreatedBy() *InviteCodeUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (_u *InviteCodeUpdateOne) Where(ps ...predicate.InviteCode) *InviteCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteCodeUpdateOne) Select(field string, fields ...string) *InviteCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteCode entity.
func (_u *InviteCodeUpdateOne) Save(ctx context.Context) (*InviteCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteCodeUpdateOne) SaveX(ctx context.Context) *InviteCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteCode.household"`)
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteCode.created_by"`)
	}
	return nil
}

func (_u *InviteCodeUpdateOne) sqlSave(ctx context.Context) (_node *InviteCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitecode.FieldID)
		for _, f := range fields {
			if !invitecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitecode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(invitecode.FieldUsed, field.TypeBool, value)
	}
	if _u.mutation.HouseholdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.HouseholdTable,
			Columns: []string{invitecode.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.HouseholdTable,
			Columns: []string{invitecode.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.CreatedByTable,
			Columns: []string{invitecode.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.CreatedByTable,
			Columns: []string{invitecode.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InviteCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
