// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/invitecode"
	"github.com/expenser/expense-planner/ent/user"
)

// InviteCodeCreate is the builder for creating a InviteCode entity.
type InviteCodeCreate struct {
	config
	mutation *InviteCodeMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *InviteCodeCreate) SetCode(v string) *InviteCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InviteCodeCreate) SetExpiresAt(v time.Time) *InviteCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsed sets the "used" field.
func (_c *InviteCodeCreate) SetUsed(v bool) *InviteCodeCreate {
	_c.mutation.SetUsed(v)
	return _c
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_c *InviteCodeCreate) SetNillableUsed(v *bool) *InviteCodeCreate {
	if v != nil {
		_c.SetUsed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteCodeCreate) SetCreatedAt(v time.Time) *InviteCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteCodeCreate) SetNillableCreatedAt(v *time.Time) *InviteCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetHouseholdID sets the "household" edge to the Household entity by ID.
func (_c *InviteCodeCreate) SetHouseholdID(id int) *InviteCodeCreate {
	_c.mutation.SetHouseholdID(id)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *InviteCodeCreate) SetHousehold(v *Household) *InviteCodeCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *InviteCodeCreate) SetCreatedByID(id int) *InviteCodeCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *InviteCodeCreate) SetCreatedBy(v *User) *InviteCodeCreate {
	return _c.SetCreatedByID(v.ID)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_c *InviteCodeCreate) Mutation() *InviteCodeMutation {
	return _c.mutation
}

// Save creates the InviteCode in the database.
func (_c *InviteCodeCreate) Save(ctx context.Context) (*InviteCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteCodeCreate) SaveX(ctx context.Context) *InviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteCodeCreate) defaults() {
	if _, ok := _c.mutation.Used(); !ok {
		v := invitecode.DefaultUsed
		_c.mutation.SetUsed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitecode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "InviteCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "InviteCode.expires_at"`)}
	}
	if _, ok := _c.mutation.Used(); !ok {
		return &ValidationError{Name: "used", err: errors.New(`ent: missing required field "InviteCode.used"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteCode.created_at"`)}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "InviteCode.household"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "InviteCode.created_by"`)}
	}
	return nil
}

func (_c *InviteCodeCreate) sqlSave(ctx context.Context) (*InviteCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteCodeCreate) createSpec() (*InviteCode, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitecode.Table, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(invitecode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Used(); ok {
		_spec.SetField(invitecode.FieldUsed, field.TypeBool, value)
		_node.Used = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitecode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.HouseholdTable,
			Columns: []string{invitecode.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.household_invite_codes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.CreatedByTable,
			Columns: []string{invitecode.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_invite_codes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InviteCodeCreateBulk is the builder for creating many InviteCode entities in bulk.
type InviteCodeCreateBulk struct {
	config
	err      error
	builders []*InviteCodeCreate
}

// Save creates the InviteCode entities in the database.
func (_c *InviteCodeCreateBulk) Save(ctx context.Context) ([]*InviteCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteCodeCreateBulk) SaveX(ctx context.Context) []*InviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
