// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/invitecode"
	"github.com/expenser/expense-planner/ent/user"
)

// InviteCode is the model entity for the InviteCode schema.
type InviteCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Used holds the value of the "used" field.
	Used bool `json:"used,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InviteCodeQuery when eager-loading is set.
	Edges                  InviteCodeEdges `json:"edges"`
	household_invite_codes *int
	user_invite_codes      *int
	selectValues           sql.SelectValues
}

// InviteCodeEdges holds the relations/edges for other nodes in the graph.
type InviteCodeEdges struct {
	// Household holds the value of the household edge.
	Household *Household `json:"household,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// HouseholdOrErr returns the Household value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteCodeEdges) HouseholdOrErr() (*Household, error) {
	if e.Household != nil {
		return e.Household, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: household.Label}
	}
	return nil, &NotLoadedError{edge: "household"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteCodeEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitecode.FieldUsed:
			values[i] = new(sql.NullBool)
		case invitecode.FieldID:
			values[i] = new(sql.NullInt64)
		case invitecode.FieldCode:
			values[i] = new(sql.NullString)
		case invitecode.FieldExpiresAt, invitecode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case invitecode.ForeignKeys[0]: // household_invite_codes
			values[i] = new(sql.NullInt64)
		case invitecode.ForeignKeys[1]: // user_invite_codes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteCode fields.
func (_m *InviteCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitecode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case invitecode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case invitecode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case invitecode.FieldUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				_m.Used = value.Bool
			}
		case invitecode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invitecode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field household_invite_codes", value)
			} else if value.Valid {
				_m.household_invite_codes = new(int)
				*_m.household_invite_codes = int(value.Int64)
			}
		case invitecode.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_invite_codes", value)
			} else if value.Valid {
				_m.user_invite_codes = new(int)
				*_m.user_invite_codes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteCode.
// This includes values selected through modifiers, order, etc.
func (_m *InviteCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHousehold queries the "household" edge of the InviteCode entity.
func (_m *InviteCode) QueryHousehold() *HouseholdQuery {
	return NewInviteCodeClient(_m.config).QueryHousehold(_m)
}

// QueryCreatedBy queries the "created_by" edge of the InviteCode entity.
func (_m *InviteCode) QueryCreatedBy() *UserQuery {
	return NewInviteCodeClient(_m.config).QueryCreatedBy(_m)
}

// Update returns a builder for updating this InviteCode.
// Note that you need to call InviteCode.Unwrap() before calling this method if this InviteCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteCode) Update() *InviteCodeUpdateOne {
	return NewInviteCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteCode) Unwrap() *InviteCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteCode) String() string {
	var builder strings.Builder
	builder.WriteString("InviteCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", _m.Used))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteCodes is a parsable slice of InviteCode.
type InviteCodes []*InviteCode
