// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/placeholder"
	"github.com/expenser/expense-planner/ent/predicate"
)

// PlaceholderUpdate is the builder for updating Placeholder entities.
type PlaceholderUpdate struct {
	config
	hooks    []Hook
	mutation *PlaceholderMutation
}

// Where appends a list predicates to the PlaceholderUpdate builder.
func (_u *PlaceholderUpdate) Where(ps ...predicate.Placeholder) *PlaceholderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the PlaceholderMutation object of the builder.
func (_u *PlaceholderUpdate) Mutation() *PlaceholderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlaceholderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaceholderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlaceholderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaceholderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlaceholderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(placeholder.Table, placeholder.Columns, sqlgraph.NewFieldSpec(placeholder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{placeholder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlaceholderUpdateOne is the builder for updating a single Placeholder entity.
type PlaceholderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaceholderMutation
}

// Mutation returns the PlaceholderMutation object of the builder.
func (_u *PlaceholderUpdateOne) Mutation() *PlaceholderMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlaceholderUpdate builder.
func (_u *PlaceholderUpdateOne) Where(ps ...predicate.Placeholder) *PlaceholderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlaceholderUpdateOne) Select(field string, fields ...string) *PlaceholderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Placeholder entity.
func (_u *PlaceholderUpdateOne) Save(ctx context.Context) (*Placeholder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaceholderUpdateOne) SaveX(ctx context.Context) *Placeholder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlaceholderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaceholderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlaceholderUpdateOne) sqlSave(ctx context.Context) (_node *Placeholder, err error) {
	_spec := sqlgraph.NewUpdateSpec(placeholder.Table, placeholder.Columns, sqlgraph.NewFieldSpec(placeholder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Placeholder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, placeholder.FieldID)
		for _, f := range fields {
			if !placeholder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != placeholder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Placeholder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{placeholder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
