// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/expenser/expense-planner/ent/category"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/predicate"
	"github.com/expenser/expense-planner/ent/recurringbill"
)

// RecurringBillQuery is the builder for querying RecurringBill entities.
type RecurringBillQuery struct {
	config
	ctx           *QueryContext
	order         []recurringbill.OrderOption
	inters        []Interceptor
	predicates    []predicate.RecurringBill
	withHousehold *HouseholdQuery
	withCategory  *CategoryQuery
	withFKs       bool
	modifiers     []func(*sql.Selector)
	loadTotal     []func(context.Context, []*RecurringBill) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecurringBillQuery builder.
func (_q *RecurringBillQuery) Where(ps ...predicate.RecurringBill) *RecurringBillQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RecurringBillQuery) Limit(limit int) *RecurringBillQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RecurringBillQuery) Offset(offset int) *RecurringBillQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RecurringBillQuery) Unique(unique bool) *RecurringBillQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RecurringBillQuery) Order(o ...recurringbill.OrderOption) *RecurringBillQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *RecurringBillQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringbill.Table, recurringbill.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringbill.HouseholdTable, recurringbill.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategory chains the current query on the "category" edge.
func (_q *RecurringBillQuery) QueryCategory() *CategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringbill.Table, recurringbill.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringbill.CategoryTable, recurringbill.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecurringBill entity from the query.
// Returns a *NotFoundError when no RecurringBill was found.
func (_q *RecurringBillQuery) First(ctx context.Context) (*RecurringBill, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recurringbill.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RecurringBillQuery) FirstX(ctx context.Context) *RecurringBill {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecurringBill ID from the query.
// Returns a *NotFoundError when no RecurringBill ID was found.
func (_q *RecurringBillQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recurringbill.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RecurringBillQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecurringBill entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecurringBill entity is found.
// Returns a *NotFoundError when no RecurringBill entities are found.
func (_q *RecurringBillQuery) Only(ctx context.Context) (*RecurringBill, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recurringbill.Label}
	default:
		return nil, &NotSingularError{recurringbill.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RecurringBillQuery) OnlyX(ctx context.Context) *RecurringBill {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecurringBill ID in the query.
// Returns a *NotSingularError when more than one RecurringBill ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RecurringBillQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recurringbill.Label}
	default:
		err = &NotSingularError{recurringbill.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RecurringBillQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecurringBills.
func (_q *RecurringBillQuery) All(ctx context.Context) ([]*RecurringBill, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecurringBill, *RecurringBillQuery]()
	return withInterceptors[[]*RecurringBill](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RecurringBillQuery) AllX(ctx context.Context) []*RecurringBill {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecurringBill IDs.
func (_q *RecurringBillQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(recurringbill.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RecurringBillQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RecurringBillQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RecurringBillQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RecurringBillQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RecurringBillQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RecurringBillQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecurringBillQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RecurringBillQuery) Clone() *RecurringBillQuery {
	if _q == nil {
		return nil
	}
	return &RecurringBillQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]recurringbill.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.RecurringBill{}, _q.predicates...),
		withHousehold: _q.withHousehold.Clone(),
		withCategory:  _q.withCategory.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecurringBillQuery) WithHousehold(opts ...func(*HouseholdQuery)) *RecurringBillQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RecurringBillQuery) WithCategory(opts ...func(*CategoryQuery)) *RecurringBillQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecurringBill.Query().
//		GroupBy(recurringbill.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RecurringBillQuery) GroupBy(field string, fields ...string) *RecurringBillGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecurringBillGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = recurringbill.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RecurringBill.Query().
//		Select(recurringbill.FieldName).
//		Scan(ctx, &v)
func (_q *RecurringBillQuery) Select(fields ...string) *RecurringBillSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RecurringBillSelect{RecurringBillQuery: _q}
	sbuild.label = recurringbill.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecurringBillSelect configured with the given aggregations.
func (_q *RecurringBillQuery) Aggregate(fns ...AggregateFunc) *RecurringBillSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RecurringBillQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !recurringbill.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RecurringBillQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecurringBill, error) {
	var (
		nodes       = []*RecurringBill{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withHousehold != nil,
			_q.withCategory != nil,
		}
	)
	if _q.withHousehold != nil || _q.withCategory != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, recurringbill.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecurringBill).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecurringBill{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *RecurringBill, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *RecurringBill, e *Category) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RecurringBillQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*RecurringBill, init func(*RecurringBill), assign func(*RecurringBill, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringBill)
	for i := range nodes {
		if nodes[i].household_recurring_bills == nil {
			continue
		}
		fk := *nodes[i].household_recurring_bills
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_recurring_bills" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RecurringBillQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*RecurringBill, init func(*RecurringBill), assign func(*RecurringBill, *Category)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringBill)
	for i := range nodes {
		if nodes[i].category_recurring_bills == nil {
			continue
		}
		fk := *nodes[i].category_recurring_bills
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_recurring_bills" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RecurringBillQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RecurringBillQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recurringbill.Table, recurringbill.Columns, sqlgraph.NewFieldSpec(recurringbill.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringbill.FieldID)
		for i := range fields {
			if fields[i] != recurringbill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RecurringBillQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(recurringbill.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = recurringbill.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecurringBillGroupBy is the group-by builder for RecurringBill entities.
type RecurringBillGroupBy struct {
	selector
	build *RecurringBillQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RecurringBillGroupBy) Aggregate(fns ...AggregateFunc) *RecurringBillGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RecurringBillGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringBillQuery, *RecurringBillGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RecurringBillGroupBy) sqlScan(ctx context.Context, root *RecurringBillQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecurringBillSelect is the builder for selecting fields of RecurringBill entities.
type RecurringBillSelect struct {
	*RecurringBillQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RecurringBillSelect) Aggregate(fns ...AggregateFunc) *RecurringBillSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RecurringBillSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringBillQuery, *RecurringBillSelect](ctx, _s.RecurringBillQuery, _s, _s.inters, v)
}

func (_s *RecurringBillSelect) sqlScan(ctx context.Context, root *RecurringBillQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
