// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/expenser/expense-planner/ent/account"
	"github.com/expenser/expense-planner/ent/budget"
	"github.com/expenser/expense-planner/ent/category"
	"github.com/expenser/expense-planner/ent/household"
	"github.com/expenser/expense-planner/ent/householdmember"
	"github.com/expenser/expense-planner/ent/recurringbill"
	"github.com/expenser/expense-planner/ent/schema"
	"github.com/expenser/expense-planner/ent/tag"
	"github.com/expenser/expense-planner/ent/transaction"
	"github.com/expenser/expense-planner/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescBalanceCents is the schema descriptor for balance_cents field.
	accountDescBalanceCents := accountFields[2].Descriptor()
	// account.DefaultBalanceCents holds the default value on creation for the balance_cents field.
	account.DefaultBalanceCents = accountDescBalanceCents.Default.(int64)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[3].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	budgetFields := schema.Budget{}.Fields()
	_ = budgetFields
	// budgetDescMonth is the schema descriptor for month field.
	budgetDescMonth := budgetFields[0].Descriptor()
	// budget.MonthValidator is a validator for the "month" field. It is called by the builders before save.
	budget.MonthValidator = budgetDescMonth.Validators[0].(func(string) error)
	// budgetDescAmountCents is the schema descriptor for amount_cents field.
	budgetDescAmountCents := budgetFields[1].Descriptor()
	// budget.AmountCentsValidator is a validator for the "amount_cents" field. It is called by the builders before save.
	budget.AmountCentsValidator = budgetDescAmountCents.Validators[0].(func(int64) error)
	// budgetDescRollover is the schema descriptor for rollover field.
	budgetDescRollover := budgetFields[2].Descriptor()
	// budget.DefaultRollover holds the default value on creation for the rollover field.
	budget.DefaultRollover = budgetDescRollover.Default.(bool)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescIsSystem is the schema descriptor for is_system field.
	categoryDescIsSystem := categoryFields[3].Descriptor()
	// category.DefaultIsSystem holds the default value on creation for the is_system field.
	category.DefaultIsSystem = categoryDescIsSystem.Default.(bool)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[4].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	householdFields := schema.Household{}.Fields()
	_ = householdFields
	// householdDescName is the schema descriptor for name field.
	householdDescName := householdFields[0].Descriptor()
	// household.NameValidator is a validator for the "name" field. It is called by the builders before save.
	household.NameValidator = householdDescName.Validators[0].(func(string) error)
	// householdDescBaseCurrency is the schema descriptor for base_currency field.
	householdDescBaseCurrency := householdFields[1].Descriptor()
	// household.DefaultBaseCurrency holds the default value on creation for the base_currency field.
	household.DefaultBaseCurrency = householdDescBaseCurrency.Default.(string)
	// household.BaseCurrencyValidator is a validator for the "base_currency" field. It is called by the builders before save.
	household.BaseCurrencyValidator = householdDescBaseCurrency.Validators[0].(func(string) error)
	// householdDescCreatedAt is the schema descriptor for created_at field.
	householdDescCreatedAt := householdFields[2].Descriptor()
	// household.DefaultCreatedAt holds the default value on creation for the created_at field.
	household.DefaultCreatedAt = householdDescCreatedAt.Default.(func() time.Time)
	householdmemberFields := schema.HouseholdMember{}.Fields()
	_ = householdmemberFields
	// householdmemberDescJoinedAt is the schema descriptor for joined_at field.
	householdmemberDescJoinedAt := householdmemberFields[1].Descriptor()
	// householdmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	householdmember.DefaultJoinedAt = householdmemberDescJoinedAt.Default.(func() time.Time)
	recurringbillFields := schema.RecurringBill{}.Fields()
	_ = recurringbillFields
	// recurringbillDescName is the schema descriptor for name field.
	recurringbillDescName := recurringbillFields[0].Descriptor()
	// recurringbill.NameValidator is a validator for the "name" field. It is called by the builders before save.
	recurringbill.NameValidator = recurringbillDescName.Validators[0].(func(string) error)
	// recurringbillDescAmountCents is the schema descriptor for amount_cents field.
	recurringbillDescAmountCents := recurringbillFields[1].Descriptor()
	// recurringbill.AmountCentsValidator is a validator for the "amount_cents" field. It is called by the builders before save.
	recurringbill.AmountCentsValidator = recurringbillDescAmountCents.Validators[0].(func(int64) error)
	// recurringbillDescDueDay is the schema descriptor for due_day field.
	recurringbillDescDueDay := recurringbillFields[2].Descriptor()
	// recurringbill.DueDayValidator is a validator for the "due_day" field. It is called by the builders before save.
	recurringbill.DueDayValidator = func() func(int) error {
		validators := recurringbillDescDueDay.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(due_day int) error {
			for _, fn := range fns {
				if err := fn(due_day); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// recurringbillDescCreatedAt is the schema descriptor for created_at field.
	recurringbillDescCreatedAt := recurringbillFields[5].Descriptor()
	// recurringbill.DefaultCreatedAt holds the default value on creation for the created_at field.
	recurringbill.DefaultCreatedAt = recurringbillDescCreatedAt.Default.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescDescription is the schema descriptor for description field.
	transactionDescDescription := transactionFields[0].Descriptor()
	// transaction.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	transaction.DescriptionValidator = transactionDescDescription.Validators[0].(func(string) error)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[3].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
