// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Placeholder is the predicate function for placeholder builders.
type Placeholder func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
