// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Budget is the predicate function for budget builders.
type Budget func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Household is the predicate function for household builders.
type Household func(*sql.Selector)

// HouseholdMember is the predicate function for householdmember builders.
type HouseholdMember func(*sql.Selector)

// InviteCode is the predicate function for invitecode builders.
type InviteCode func(*sql.Selector)

// Placeholder is the predicate function for placeholder builders.
type Placeholder func(*sql.Selector)

// RecurringBill is the predicate function for recurringbill builders.
type RecurringBill func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// TransactionEntry is the predicate function for transactionentry builders.
type TransactionEntry func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
